// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0
//
// AUTO-GENERATED by types/scripts/ai-types/generate.ts
// DO NOT EDIT MANUALLY. Run `pnpm generate` to regenerate.

export interface AiJsonModeResponseFormat {
  type?: 'json_object' | 'json_schema';
  json_schema?: unknown;
}

/**
 * Usage statistics for the inference request
 */
export interface AiUsageUsage {
  /**
   * Total number of tokens in input
   */
  prompt_tokens?: number;
  /**
   * Total number of tokens in output
   */
  completion_tokens?: number;
  /**
   * Total number of input and output tokens
   */
  total_tokens?: number;
}

export interface AiToolCallOutputToolCall {
  /**
   * Unique identifier for the tool call
   */
  id: string;
  /**
   * Type of tool call
   */
  type: 'function';
  function: {
    /**
     * Name of the function to call
     */
    name: string;
    /**
     * JSON string of arguments for the function
     */
    arguments: string;
  };
}

export type AiTextGenerationInput =
  | ({
      prompt: AiTextGenerationPromptsPrompt;
      lora?: AiTextGenerationFinetuneLora;
      response_format?: AiJsonModeResponseFormat;
    } & AiTextGenerationOptionsCommon)
  | ({
      messages: AiTextGenerationPromptsMessages;
      functions?: AiTextGenerationToolsFunctions;
      tools?: AiTextGenerationToolsTools;
      response_format?: AiJsonModeResponseFormat;
    } & AiTextGenerationOptionsCommon);

export type AiTextGenerationOutput =
  | {
      /**
       * The generated text response from the model
       */
      response: string;
      usage?: AiUsageUsage;
      /**
       * An array of tool calls requests made during the response generation
       */
      tool_calls?: {
        /**
         * The arguments passed to be passed to the tool call request
         */
        arguments?: {};
        /**
         * The name of the tool to be called
         */
        name?: string;
      }[];
    }
  | string;

/**
 * The input text prompt for the model to generate a response.
 */
export type AiTextGenerationPromptsPrompt = string;

/**
 * An array of message objects representing the conversation history.
 */
export type AiTextGenerationPromptsMessages = {
  /**
   * The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').
   */
  role: string;
  content:
    | string
    | {
        /**
         * Type of the content (text)
         */
        type?: string;
        /**
         * Text content
         */
        text?: string;
      }[];
}[];

/**
 * An array of message objects representing the conversation history.
 */
export type AiTextGenerationPromptsVisionMessages = {
  /**
   * The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').
   */
  role: string;
  /**
   * The tool call id.
   */
  tool_call_id?: string;
  content:
    | string
    | {
        /**
         * Type of the content provided
         */
        type?: string;
        image_url?: {
          /**
           * image uri with data (e.g. data:image/jpeg;base64,/9j/...). HTTP URL will not be accepted
           */
          url?: string;
        };
      }[]
    | {
        /**
         * Type of the content provided
         */
        type?: string;
        image_url?: {
          /**
           * image uri with data (e.g. data:image/jpeg;base64,/9j/...). HTTP URL will not be accepted
           */
          url?: string;
        };
      };
}[];

export interface AiTextGenerationOptionsCommon {
  /**
   * If true, a chat template is not applied and you must adhere to the specific model's expected formatting.
   */
  raw?: boolean;
  /**
   * If true, the response will be streamed back incrementally using SSE, Server Sent Events.
   */
  stream?: boolean;
  /**
   * The maximum number of tokens to generate in the response.
   */
  max_tokens?: number;
  /**
   * Controls the randomness of the output; higher values produce more random results.
   */
  temperature?: number;
  /**
   * Adjusts the creativity of the AI's responses by controlling how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.
   */
  top_p?: number;
  /**
   * Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.
   */
  top_k?: number;
  /**
   * Random seed for reproducibility of the generation.
   */
  seed?: number;
  /**
   * Penalty for repeated tokens; higher values discourage repetition.
   */
  repetition_penalty?: number;
  /**
   * Decreases the likelihood of the model repeating the same lines verbatim.
   */
  frequency_penalty?: number;
  /**
   * Increases the likelihood of the model introducing new topics.
   */
  presence_penalty?: number;
}

export type AiTextGenerationToolsFunctions = {
  name: string;
  code: string;
}[];

/**
 * A list of tools available for the assistant to use.
 */
export type AiTextGenerationToolsTools = (
  | {
      /**
       * The name of the tool. More descriptive the better.
       */
      name: string;
      /**
       * A brief description of what the tool does.
       */
      description: string;
      /**
       * Schema defining the parameters accepted by the tool.
       */
      parameters: {
        /**
         * The type of the parameters object (usually 'object').
         */
        type: string;
        /**
         * List of required parameter names.
         */
        required?: string[];
        /**
         * Definitions of each parameter.
         */
        properties: {
          [k: string]: {
            /**
             * The data type of the parameter.
             */
            type: string;
            /**
             * A description of the expected parameter.
             */
            description: string;
          };
        };
      };
    }
  | {
      /**
       * Specifies the type of tool (e.g., 'function').
       */
      type: string;
      /**
       * Details of the function tool.
       */
      function: {
        /**
         * The name of the function.
         */
        name: string;
        /**
         * A brief description of what the function does.
         */
        description: string;
        /**
         * Schema defining the parameters accepted by the function.
         */
        parameters: {
          /**
           * The type of the parameters object (usually 'object').
           */
          type: string;
          /**
           * List of required parameter names.
           */
          required?: string[];
          /**
           * Definitions of each parameter.
           */
          properties: {
            [k: string]: {
              /**
               * The data type of the parameter.
               */
              type: string;
              /**
               * A description of the expected parameter.
               */
              description: string;
            };
          };
        };
      };
    }
)[];

/**
 * Name of the LoRA (Low-Rank Adaptation) model to fine-tune the base model.
 */
export type AiTextGenerationFinetuneLora = string;

export interface AiTextEmbeddingsInput {
  text: string | string[];
}

export interface AiTextEmbeddingsOutput {
  shape?: number[];
  /**
   * Embeddings of the requested text values
   */
  data?: number[][];
}

/**
 *  pooling method used in the embedding process. Note that the `mean` method should not be used in the bge*-v1.5 family and it's a default simply for backwards compatibility reasons.
 */
export type AiTextEmbeddingsPoolingPooling = 'mean' | 'cls';

export type AiResponsesInput =
  | AiResponsesBasicInput
  | {
      requests: Input[];
    };
export type Input = AiResponsesBasicInput;

export interface AiResponsesOutput {
  id?: string;
  created_at?: number;
  output_text?: string;
  error?: AiResponsesBasicResponseError;
  incomplete_details?: AiResponsesBasicResponseIncompleteDetails;
  instructions?: string | AiResponsesMessagesResponseInputItem[];
  object?: string;
  output?: AiResponsesOutputResponseOutputItem[];
  parallel_tool_calls?: boolean;
  temperature?: number;
  tool_choice?:
    | AiResponsesToolChoiceToolChoiceOptions
    | AiResponsesToolChoiceToolChoiceFunction;
  tools?: AiResponsesToolDefinitionsTool[];
  top_p?: number;
  max_output_tokens?: number;
  previous_response_id?: string;
  prompt?: AiResponsesBasicResponsePrompt;
  reasoning?: AiResponsesReasoningReasoning;
  safety_identifier?: string;
  service_tier?: 'auto' | 'default' | 'flex' | 'scale' | 'priority';
  status?: AiResponsesBasicResponseStatus;
  text?: AiResponsesTextConfigResponseTextConfig;
  truncation?: 'auto' | 'disabled';
  usage?: AiResponsesBasicResponseUsage;
}

export interface AiResponsesBasicInput {
  background?: boolean;
  conversation?: string | AiResponsesBasicResponseConversationParam;
  include?: AiResponsesBasicResponseIncludable[];
  input: string | AiResponsesMessagesResponseInput;
  instructions?: string;
  max_output_tokens?: number;
  parallel_tool_calls?: boolean;
  previous_response_id?: string;
  prompt_cache_key?: string;
  reasoning?: AiResponsesReasoningReasoning;
  safety_identifier?: string;
  service_tier?: 'auto' | 'default' | 'flex' | 'scale' | 'priority';
  stream?: boolean;
  stream_options?: AiResponsesBasicStreamOptions;
  temperature?: number;
  text?: AiResponsesTextConfigResponseTextConfig;
  tool_choice?:
    | AiResponsesToolChoiceToolChoiceOptions
    | AiResponsesToolChoiceToolChoiceFunction;
  tools?: AiResponsesToolDefinitionsTool[];
  top_p?: number;
  truncation?: 'auto' | 'disabled';
}

export interface AiResponsesBasicResponseConversationParam {
  id: string;
}

export type AiResponsesBasicResponseIncludable =
  | 'message.input_image.image_url'
  | 'message.output_text.logprobs';

export interface AiResponsesBasicStreamOptions {
  include_obfuscation?: boolean;
}

export type AiResponsesBasicResponseStatus =
  | 'completed'
  | 'failed'
  | 'in_progress'
  | 'cancelled'
  | 'queued'
  | 'incomplete';

export interface AiResponsesBasicResponseUsage {
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
}

export interface AiResponsesBasicResponseError {
  code:
    | 'server_error'
    | 'rate_limit_exceeded'
    | 'invalid_prompt'
    | 'vector_store_timeout'
    | 'invalid_image'
    | 'invalid_image_format'
    | 'invalid_base64_image'
    | 'invalid_image_url'
    | 'image_too_large'
    | 'image_too_small'
    | 'image_parse_error'
    | 'image_content_policy_violation'
    | 'invalid_image_mode'
    | 'image_file_too_large'
    | 'unsupported_image_media_type'
    | 'empty_image_file'
    | 'failed_to_download_image'
    | 'image_file_not_found';
  message: string;
}

export interface AiResponsesBasicResponseIncompleteDetails {
  reason?: 'max_output_tokens' | 'content_filter';
}

export interface AiResponsesBasicResponsePrompt {
  id: string;
  variables?: {
    [k: string]:
      | string
      | AiResponsesInputContentResponseInputText
      | AiResponsesInputContentResponseInputImage;
  };
  version?: string;
}

export interface AiResponsesTextFormatsResponseFormatText {
  type: string;
}

export interface AiResponsesTextFormatsResponseFormatTextJSONSchemaConfig {
  name: string;
  schema: {};
  type: string;
  description?: string;
  strict?: boolean;
}

export interface AiResponsesTextFormatsResponseFormatJSONObject {
  type: string;
}

export interface AiResponsesTextConfigResponseTextConfig {
  format?: AiResponsesTextConfigResponseFormatTextConfig;
  verbosity?: 'low' | 'medium' | 'high';
}

export type AiResponsesTextConfigResponseFormatTextConfig =
  | AiResponsesTextFormatsResponseFormatText
  | AiResponsesTextFormatsResponseFormatTextJSONSchemaConfig
  | AiResponsesTextFormatsResponseFormatJSONObject;

export type AiResponsesToolChoiceToolChoiceOptions = string;

export interface AiResponsesToolChoiceToolChoiceFunction {
  name: string;
  type: string;
}

export type AiResponsesToolDefinitionsTool =
  AiResponsesToolDefinitionsResponsesFunctionTool;

export interface AiResponsesToolDefinitionsResponsesFunctionTool {
  name: string;
  parameters: {};
  strict: boolean;
  type: string;
  description?: string;
}

export interface AiResponsesToolCallsResponseFunctionToolCall {
  arguments: string;
  call_id: string;
  name: string;
  type: string;
  id?: string;
  status?: 'in_progress' | 'completed' | 'incomplete';
}

export interface AiResponsesToolCallsResponseInputItemFunctionCallOutput {
  call_id: string;
  output: string | AiResponsesToolCallsResponseFunctionCallOutputItemList;
  type: string;
  id?: string;
  status?: 'in_progress' | 'completed' | 'incomplete';
}

export type AiResponsesToolCallsResponseFunctionCallOutputItemList =
  AiResponsesToolCallsResponseFunctionCallOutputItem[];

export type AiResponsesToolCallsResponseFunctionCallOutputItem =
  | AiResponsesInputContentResponseInputTextContent
  | AiResponsesInputContentResponseInputImageContent;

export interface AiResponsesLogprobsLogprob {
  token: string;
  logprob: number;
  top_logprobs?: AiResponsesLogprobsTopLogprob[];
}

export interface AiResponsesLogprobsTopLogprob {
  token?: string;
  logprob?: number;
}

export interface AiResponsesInputContentResponseInputText {
  text: string;
  type: string;
}

export interface AiResponsesInputContentResponseInputImage {
  detail: 'low' | 'high' | 'auto';
  type: string;
  /**
   * Base64 encoded image
   */
  image_url?: string;
}

export interface AiResponsesInputContentResponseInputTextContent {
  text: string;
  type: string;
}

export interface AiResponsesInputContentResponseInputImageContent {
  type: string;
  detail?: 'low' | 'high' | 'auto';
  /**
   * Base64 encoded image
   */
  image_url?: string;
}

export type AiResponsesInputContentResponseInputContent =
  | AiResponsesInputContentResponseInputText
  | AiResponsesInputContentResponseInputImage;

export type AiResponsesInputContentResponseInputMessageContentList =
  AiResponsesInputContentResponseInputContent[];

export interface AiResponsesOutputContentResponseOutputText {
  text: string;
  type: string;
  logprobs?: AiResponsesLogprobsLogprob[];
}

export interface AiResponsesOutputContentResponseOutputRefusal {
  refusal: string;
  type: string;
}

export type AiResponsesMessagesResponseInput =
  AiResponsesMessagesResponseInputItem[];

export type AiResponsesMessagesResponseInputItem =
  | AiResponsesMessagesEasyInputMessage
  | AiResponsesMessagesResponseInputItemMessage
  | AiResponsesMessagesResponseOutputMessage
  | AiResponsesToolCallsResponseFunctionToolCall
  | AiResponsesToolCallsResponseInputItemFunctionCallOutput
  | AiResponsesReasoningResponseReasoningItem;

export interface AiResponsesMessagesEasyInputMessage {
  content: string | AiResponsesInputContentResponseInputMessageContentList;
  role: 'user' | 'assistant' | 'system' | 'developer';
  type?: string;
}

export interface AiResponsesMessagesResponseInputItemMessage {
  content: AiResponsesInputContentResponseInputMessageContentList;
  role: 'user' | 'system' | 'developer';
  status?: 'in_progress' | 'completed' | 'incomplete';
  type?: string;
}

export interface AiResponsesMessagesResponseOutputMessage {
  id: string;
  content: (
    | AiResponsesOutputContentResponseOutputText
    | AiResponsesOutputContentResponseOutputRefusal
  )[];
  role: string;
  status: 'in_progress' | 'completed' | 'incomplete';
  type: string;
}

export interface AiResponsesReasoningReasoning {
  effort?: AiResponsesReasoningReasoningEffort;
  generate_summary?: 'auto' | 'concise' | 'detailed';
  summary?: 'auto' | 'concise' | 'detailed';
}

export type AiResponsesReasoningReasoningEffort =
  | 'minimal'
  | 'low'
  | 'medium'
  | 'high';

export interface AiResponsesReasoningResponseReasoningItem {
  id: string;
  summary: AiResponsesReasoningResponseReasoningSummaryItem[];
  type: string;
  content?: AiResponsesReasoningResponseReasoningContentItem[];
  encrypted_content?: string;
  status?: 'in_progress' | 'completed' | 'incomplete';
}

export interface AiResponsesReasoningResponseReasoningSummaryItem {
  text: string;
  type: string;
}

export interface AiResponsesReasoningResponseReasoningContentItem {
  text: string;
  type: string;
}

export type AiResponsesOutputResponseOutputItem =
  | AiResponsesMessagesResponseOutputMessage
  | AiResponsesToolCallsResponseFunctionToolCall
  | AiResponsesReasoningResponseReasoningItem;

export type AiChatCompletionsInput =
  | ({
      /**
       * The input text prompt for the model to generate a response.
       */
      prompt: string;
    } & AiChatCompletionsOptionsCommon)
  | ({
      /**
       * A list of messages comprising the conversation so far.
       *
       * @minItems 1
       */
      messages: [
        AiChatCompletionsMessagesChatCompletionMessageParam,
        ...AiChatCompletionsMessagesChatCompletionMessageParam[],
      ];
    } & AiChatCompletionsOptionsCommon);

export type AiChatCompletionsOutput =
  | {
      /**
       * A unique identifier for the chat completion.
       */
      id: string;
      object: string;
      /**
       * Unix timestamp (seconds) of when the completion was created.
       */
      created: number;
      /**
       * The model used for the chat completion.
       */
      model: string;
      /**
       * @minItems 1
       */
      choices: [
        AiChatCompletionsResponseChatCompletionChoice,
        ...AiChatCompletionsResponseChatCompletionChoice[],
      ];
      usage?: AiChatCompletionsResponseCompletionUsage;
      system_fingerprint?: string | null;
      service_tier?:
        | ('auto' | 'default' | 'flex' | 'scale' | 'priority')
        | null;
    }
  | string;

export interface AiChatCompletionsContentPartsChatCompletionContentPartText {
  type: 'text';
  text: string;
}

export interface AiChatCompletionsContentPartsChatCompletionContentPartImage {
  type: 'image_url';
  image_url: {
    url: string;
    detail?: 'auto' | 'low' | 'high';
  };
}

export interface AiChatCompletionsContentPartsChatCompletionContentPartInputAudio {
  type: 'input_audio';
  input_audio: {
    /**
     * Base64 encoded audio data.
     */
    data: string;
    format: 'wav' | 'mp3';
  };
}

export interface AiChatCompletionsContentPartsChatCompletionContentPartFile {
  type: 'file';
  file: {
    /**
     * Base64 encoded file data.
     */
    file_data?: string;
    /**
     * The ID of an uploaded file.
     */
    file_id?: string;
    filename?: string;
  };
}

export interface AiChatCompletionsContentPartsChatCompletionContentPartRefusal {
  type: 'refusal';
  refusal: string;
}

/**
 * A content part in a user message (text, image, audio, or file).
 */
export type AiChatCompletionsContentPartsChatCompletionContentPart =
  | AiChatCompletionsContentPartsChatCompletionContentPartText
  | AiChatCompletionsContentPartsChatCompletionContentPartImage
  | AiChatCompletionsContentPartsChatCompletionContentPartInputAudio
  | AiChatCompletionsContentPartsChatCompletionContentPartFile;

export interface AiChatCompletionsMessagesDeveloperMessage {
  role: 'developer';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
  name?: string;
}

export interface AiChatCompletionsMessagesSystemMessage {
  role: 'system';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
  name?: string;
}

export interface AiChatCompletionsMessagesUserMessage {
  role: 'user';
  content:
    | string
    | [
        {
          type: 'text' | 'image_url' | 'input_audio' | 'file';
          text?: string;
          image_url?: {
            url?: string;
            detail?: 'auto' | 'low' | 'high';
          };
          input_audio?: {
            data?: string;
            format?: 'wav' | 'mp3';
          };
          file?: {
            file_data?: string;
            file_id?: string;
            filename?: string;
          };
        },
        ...{
          type: 'text' | 'image_url' | 'input_audio' | 'file';
          text?: string;
          image_url?: {
            url?: string;
            detail?: 'auto' | 'low' | 'high';
          };
          input_audio?: {
            data?: string;
            format?: 'wav' | 'mp3';
          };
          file?: {
            file_data?: string;
            file_id?: string;
            filename?: string;
          };
        }[],
      ];
  name?: string;
}

export interface AiChatCompletionsMessagesAssistantMessage {
  role: 'assistant';
  content?:
    | string
    | null
    | {
        type: 'text' | 'refusal';
        text?: string;
        refusal?: string;
      }[];
  refusal?: string | null;
  name?: string;
  audio?: {
    id: string;
  };
  tool_calls?: AiChatCompletionsToolsChatCompletionMessageToolCall[];
  function_call?: {
    name: string;
    arguments: string;
  };
}

export interface AiChatCompletionsMessagesToolMessage {
  role: 'tool';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
  tool_call_id: string;
}

export interface AiChatCompletionsMessagesFunctionMessage {
  role: 'function';
  content: string;
  name: string;
}

export type AiChatCompletionsMessagesChatCompletionMessageParam =
  | AiChatCompletionsMessagesDeveloperMessage
  | AiChatCompletionsMessagesSystemMessage
  | AiChatCompletionsMessagesUserMessage
  | AiChatCompletionsMessagesAssistantMessage
  | AiChatCompletionsMessagesToolMessage
  | AiChatCompletionsMessagesFunctionMessage;

export interface AiChatCompletionsToolsFunctionDefinition {
  /**
   * The name of the function to be called.
   */
  name: string;
  /**
   * A description of what the function does.
   */
  description?: string;
  /**
   * The parameters the function accepts, described as a JSON Schema object.
   */
  parameters?: {};
  /**
   * Whether to enable strict schema adherence.
   */
  strict?: boolean | null;
}

export interface AiChatCompletionsToolsChatCompletionFunctionTool {
  type: 'function';
  function: AiChatCompletionsToolsFunctionDefinition;
}

export interface AiChatCompletionsToolsChatCompletionCustomTool {
  type: 'custom';
  custom: {
    name: string;
    description?: string;
    format?:
      | {
          type: 'text';
        }
      | {
          type: 'grammar';
          grammar: {
            definition: string;
            syntax: 'lark' | 'regex';
          };
        };
  };
}

export type AiChatCompletionsToolsChatCompletionTool =
  | AiChatCompletionsToolsChatCompletionFunctionTool
  | AiChatCompletionsToolsChatCompletionCustomTool;

export interface AiChatCompletionsToolsChatCompletionMessageFunctionToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    /**
     * JSON-encoded arguments string.
     */
    arguments: string;
  };
}

export interface AiChatCompletionsToolsChatCompletionMessageCustomToolCall {
  id: string;
  type: 'custom';
  custom: {
    name: string;
    input: string;
  };
}

export type AiChatCompletionsToolsChatCompletionMessageToolCall =
  | AiChatCompletionsToolsChatCompletionMessageFunctionToolCall
  | AiChatCompletionsToolsChatCompletionMessageCustomToolCall;

/**
 * Controls which (if any) tool is called by the model. 'none' = no tools, 'auto' = model decides, 'required' = must call a tool.
 */
export type AiChatCompletionsToolsChatCompletionToolChoiceOption =
  | ('none' | 'auto' | 'required')
  | {
      type: 'function';
      function: {
        name: string;
      };
    }
  | {
      type: 'custom';
      custom: {
        name: string;
      };
    }
  | {
      type: 'allowed_tools';
      allowed_tools: {
        mode: 'auto' | 'required';
        tools: {}[];
      };
    };

/**
 * Specifies the format the model must output.
 */
export type AiChatCompletionsOptionsResponseFormat =
  | {
      type: 'text';
    }
  | {
      type: 'json_object';
    }
  | {
      type: 'json_schema';
      json_schema: {
        name: string;
        description?: string;
        schema?: {};
        strict?: boolean | null;
      };
    };

export interface AiChatCompletionsOptionsStreamOptions {
  include_usage?: boolean;
  include_obfuscation?: boolean;
}

export interface AiChatCompletionsOptionsPredictionContent {
  type: 'content';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
}

/**
 * Parameters for audio output. Required when modalities includes 'audio'.
 */
export interface AiChatCompletionsOptionsAudioParams {
  voice:
    | string
    | {
        id: string;
      };
  format: 'wav' | 'aac' | 'mp3' | 'flac' | 'opus' | 'pcm16';
}

/**
 * Options for the web search tool (when using built-in web search).
 */
export interface AiChatCompletionsOptionsWebSearchOptions {
  search_context_size?: 'low' | 'medium' | 'high';
  user_location?: {
    type: 'approximate';
    approximate: {
      city?: string;
      country?: string;
      region?: string;
      timezone?: string;
    };
  };
}

export interface AiChatCompletionsOptionsCommon {
  /**
   * ID of the model to use (e.g. '@cf/zai-org/glm-4.7-flash, etc').
   */
  model?: string;
  audio?: AiChatCompletionsOptionsAudioParams;
  /**
   * Penalizes new tokens based on their existing frequency in the text so far.
   */
  frequency_penalty?: number | null;
  /**
   * Modify the likelihood of specified tokens appearing in the completion. Maps token IDs to bias values from -100 to 100.
   */
  logit_bias?: {} | null;
  /**
   * Whether to return log probabilities of the output tokens.
   */
  logprobs?: boolean | null;
  /**
   * How many top log probabilities to return at each token position (0-20). Requires logprobs=true.
   */
  top_logprobs?: number | null;
  /**
   * Deprecated in favor of max_completion_tokens. The maximum number of tokens to generate.
   */
  max_tokens?: number | null;
  /**
   * An upper bound for the number of tokens that can be generated for a completion.
   */
  max_completion_tokens?: number | null;
  /**
   * Set of 16 key-value pairs that can be attached to the object.
   */
  metadata?: {} | null;
  /**
   * Output types requested from the model (e.g. ['text'] or ['text', 'audio']).
   */
  modalities?: ('text' | 'audio')[] | null;
  /**
   * How many chat completion choices to generate for each input message.
   */
  n?: number | null;
  /**
   * Whether to enable parallel function calling during tool use.
   */
  parallel_tool_calls?: boolean;
  prediction?: AiChatCompletionsOptionsPredictionContent;
  /**
   * Penalizes new tokens based on whether they appear in the text so far.
   */
  presence_penalty?: number | null;
  /**
   * Constrains effort on reasoning for reasoning models (o1, o3-mini, etc.).
   */
  reasoning_effort?: ('low' | 'medium' | 'high') | null;
  chat_template_kwargs?: {
    /**
     * Whether to enable reasoning, enabled by default.
     */
    enable_thinking?: boolean;
    /**
     * If false, preserves reasoning context between turns.
     */
    clear_thinking?: boolean;
  };
  response_format?: AiChatCompletionsOptionsResponseFormat;
  /**
   * If specified, the system will make a best effort to sample deterministically.
   */
  seed?: number | null;
  /**
   * Specifies the processing type used for serving the request.
   */
  service_tier?: ('auto' | 'default' | 'flex' | 'scale' | 'priority') | null;
  /**
   * Up to 4 sequences where the API will stop generating further tokens.
   */
  stop?:
    | null
    | string
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string];
  /**
   * Whether to store the output for model distillation / evals.
   */
  store?: boolean | null;
  /**
   * If true, partial message deltas will be sent as server-sent events.
   */
  stream?: boolean | null;
  stream_options?: AiChatCompletionsOptionsStreamOptions;
  /**
   * Sampling temperature between 0 and 2.
   */
  temperature?: number | null;
  tool_choice?: AiChatCompletionsToolsChatCompletionToolChoiceOption;
  /**
   * A list of tools the model may call.
   */
  tools?: AiChatCompletionsToolsChatCompletionTool[];
  /**
   * Nucleus sampling: considers the results of the tokens with top_p probability mass.
   */
  top_p?: number | null;
  /**
   * A unique identifier representing your end-user, for abuse monitoring.
   */
  user?: string;
  web_search_options?: AiChatCompletionsOptionsWebSearchOptions;
  function_call?:
    | ('none' | 'auto')
    | {
        name: string;
      };
  /**
   * @minItems 1
   * @maxItems 128
   */
  functions?: [
    AiChatCompletionsToolsFunctionDefinition,
    ...AiChatCompletionsToolsFunctionDefinition[],
  ];
}

export interface AiChatCompletionsResponseCompletionUsage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  prompt_tokens_details?: {
    cached_tokens?: number;
    audio_tokens?: number;
  };
  completion_tokens_details?: {
    reasoning_tokens?: number;
    audio_tokens?: number;
    accepted_prediction_tokens?: number;
    rejected_prediction_tokens?: number;
  };
}

export interface AiChatCompletionsResponseChatCompletionTokenLogprob {
  token: string;
  logprob: number;
  bytes: number[] | null;
  top_logprobs: {
    token: string;
    logprob: number;
    bytes: number[] | null;
  }[];
}

export interface AiChatCompletionsResponseChatCompletionAudio {
  id: string;
  /**
   * Base64 encoded audio bytes.
   */
  data: string;
  expires_at: number;
  transcript: string;
}

export interface AiChatCompletionsResponseChatCompletionResponseMessage {
  role: 'assistant';
  content: string | null;
  refusal: string | null;
  annotations?: {
    type: 'url_citation';
    url_citation: {
      url: string;
      title: string;
      start_index: number;
      end_index: number;
    };
  }[];
  audio?: AiChatCompletionsResponseChatCompletionAudio;
  tool_calls?: AiChatCompletionsToolsChatCompletionMessageToolCall[];
  function_call?: {
    name: string;
    arguments: string;
  } | null;
}

export interface AiChatCompletionsResponseChatCompletionChoice {
  index: number;
  message: AiChatCompletionsResponseChatCompletionResponseMessage;
  finish_reason:
    | 'stop'
    | 'length'
    | 'tool_calls'
    | 'content_filter'
    | 'function_call';
  logprobs: {
    content?: AiChatCompletionsResponseChatCompletionTokenLogprob[] | null;
    refusal?: AiChatCompletionsResponseChatCompletionTokenLogprob[] | null;
  } | null;
}
