// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0
//
// AUTO-GENERATED by types/scripts/ai-types/generate.ts
// DO NOT EDIT MANUALLY. Run `pnpm generate` to regenerate.

interface _AiJsonModeResponseFormat {
  type?: 'json_object' | 'json_schema';
  json_schema?: unknown;
}

/**
 * Usage statistics for the inference request
 */
interface _AiUsageUsage {
  /**
   * Total number of tokens in input
   */
  prompt_tokens?: number;
  /**
   * Total number of tokens in output
   */
  completion_tokens?: number;
  /**
   * Total number of input and output tokens
   */
  total_tokens?: number;
}

interface _AiToolCallOutputToolCall {
  /**
   * Unique identifier for the tool call
   */
  id: string;
  /**
   * Type of tool call
   */
  type: 'function';
  function: {
    /**
     * Name of the function to call
     */
    name: string;
    /**
     * JSON string of arguments for the function
     */
    arguments: string;
  };
}

type _AiTextGenerationInput =
  | ({
      prompt: _AiTextGenerationPromptsPrompt;
      lora?: _AiTextGenerationFinetuneLora;
      response_format?: _AiJsonModeResponseFormat;
    } & _AiTextGenerationOptionsCommon)
  | ({
      messages: _AiTextGenerationPromptsMessages;
      functions?: _AiTextGenerationToolsFunctions;
      tools?: _AiTextGenerationToolsTools;
      response_format?: _AiJsonModeResponseFormat;
    } & _AiTextGenerationOptionsCommon);

type _AiTextGenerationOutput =
  | {
      /**
       * The generated text response from the model
       */
      response: string;
      usage?: _AiUsageUsage;
      /**
       * An array of tool calls requests made during the response generation
       */
      tool_calls?: {
        /**
         * The arguments passed to be passed to the tool call request
         */
        arguments?: {};
        /**
         * The name of the tool to be called
         */
        name?: string;
      }[];
    }
  | string;

/**
 * The input text prompt for the model to generate a response.
 */
type _AiTextGenerationPromptsPrompt = string;

/**
 * An array of message objects representing the conversation history.
 */
type _AiTextGenerationPromptsMessages = {
  /**
   * The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').
   */
  role: string;
  content:
    | string
    | {
        /**
         * Type of the content (text)
         */
        type?: string;
        /**
         * Text content
         */
        text?: string;
      }[];
}[];

/**
 * An array of message objects representing the conversation history.
 */
type _AiTextGenerationPromptsVisionMessages = {
  /**
   * The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').
   */
  role: string;
  /**
   * The tool call id.
   */
  tool_call_id?: string;
  content:
    | string
    | {
        /**
         * Type of the content provided
         */
        type?: string;
        image_url?: {
          /**
           * image uri with data (e.g. data:image/jpeg;base64,/9j/...). HTTP URL will not be accepted
           */
          url?: string;
        };
      }[]
    | {
        /**
         * Type of the content provided
         */
        type?: string;
        image_url?: {
          /**
           * image uri with data (e.g. data:image/jpeg;base64,/9j/...). HTTP URL will not be accepted
           */
          url?: string;
        };
      };
}[];

interface _AiTextGenerationOptionsCommon {
  /**
   * If true, a chat template is not applied and you must adhere to the specific model's expected formatting.
   */
  raw?: boolean;
  /**
   * If true, the response will be streamed back incrementally using SSE, Server Sent Events.
   */
  stream?: boolean;
  /**
   * The maximum number of tokens to generate in the response.
   */
  max_tokens?: number;
  /**
   * Controls the randomness of the output; higher values produce more random results.
   */
  temperature?: number;
  /**
   * Adjusts the creativity of the AI's responses by controlling how many possible words it considers. Lower values make outputs more predictable; higher values allow for more varied and creative responses.
   */
  top_p?: number;
  /**
   * Limits the AI to choose from the top 'k' most probable words. Lower values make responses more focused; higher values introduce more variety and potential surprises.
   */
  top_k?: number;
  /**
   * Random seed for reproducibility of the generation.
   */
  seed?: number;
  /**
   * Penalty for repeated tokens; higher values discourage repetition.
   */
  repetition_penalty?: number;
  /**
   * Decreases the likelihood of the model repeating the same lines verbatim.
   */
  frequency_penalty?: number;
  /**
   * Increases the likelihood of the model introducing new topics.
   */
  presence_penalty?: number;
}

type _AiTextGenerationToolsFunctions = {
  name: string;
  code: string;
}[];

/**
 * A list of tools available for the assistant to use.
 */
type _AiTextGenerationToolsTools = (
  | {
      /**
       * The name of the tool. More descriptive the better.
       */
      name: string;
      /**
       * A brief description of what the tool does.
       */
      description: string;
      /**
       * Schema defining the parameters accepted by the tool.
       */
      parameters: {
        /**
         * The type of the parameters object (usually 'object').
         */
        type: string;
        /**
         * List of required parameter names.
         */
        required?: string[];
        /**
         * Definitions of each parameter.
         */
        properties: {
          [k: string]: {
            /**
             * The data type of the parameter.
             */
            type: string;
            /**
             * A description of the expected parameter.
             */
            description: string;
          };
        };
      };
    }
  | {
      /**
       * Specifies the type of tool (e.g., 'function').
       */
      type: string;
      /**
       * Details of the function tool.
       */
      function: {
        /**
         * The name of the function.
         */
        name: string;
        /**
         * A brief description of what the function does.
         */
        description: string;
        /**
         * Schema defining the parameters accepted by the function.
         */
        parameters: {
          /**
           * The type of the parameters object (usually 'object').
           */
          type: string;
          /**
           * List of required parameter names.
           */
          required?: string[];
          /**
           * Definitions of each parameter.
           */
          properties: {
            [k: string]: {
              /**
               * The data type of the parameter.
               */
              type: string;
              /**
               * A description of the expected parameter.
               */
              description: string;
            };
          };
        };
      };
    }
)[];

/**
 * Name of the LoRA (Low-Rank Adaptation) model to fine-tune the base model.
 */
type _AiTextGenerationFinetuneLora = string;

interface _AiTextEmbeddingsInput {
  text: string | string[];
}

interface _AiTextEmbeddingsOutput {
  shape?: number[];
  /**
   * Embeddings of the requested text values
   */
  data?: number[][];
}

/**
 *  pooling method used in the embedding process. Note that the `mean` method should not be used in the bge*-v1.5 family and it's a default simply for backwards compatibility reasons.
 */
type _AiTextEmbeddingsPoolingPooling = 'mean' | 'cls';

type _AiResponsesInput =
  | _AiResponsesBasicInput
  | {
      requests: Input[];
    };
type Input = _AiResponsesBasicInput;

interface _AiResponsesOutput {
  id?: string;
  created_at?: number;
  output_text?: string;
  error?: _AiResponsesBasicResponseError;
  incomplete_details?: _AiResponsesBasicResponseIncompleteDetails;
  instructions?: string | _AiResponsesMessagesResponseInputItem[];
  object?: string;
  output?: _AiResponsesOutputResponseOutputItem[];
  parallel_tool_calls?: boolean;
  temperature?: number;
  tool_choice?:
    | _AiResponsesToolChoiceToolChoiceOptions
    | _AiResponsesToolChoiceToolChoiceFunction;
  tools?: _AiResponsesToolDefinitionsTool[];
  top_p?: number;
  max_output_tokens?: number;
  previous_response_id?: string;
  prompt?: _AiResponsesBasicResponsePrompt;
  reasoning?: _AiResponsesReasoningReasoning;
  safety_identifier?: string;
  service_tier?: 'auto' | 'default' | 'flex' | 'scale' | 'priority';
  status?: _AiResponsesBasicResponseStatus;
  text?: _AiResponsesTextConfigResponseTextConfig;
  truncation?: 'auto' | 'disabled';
  usage?: _AiResponsesBasicResponseUsage;
}

interface _AiResponsesBasicInput {
  background?: boolean;
  conversation?: string | _AiResponsesBasicResponseConversationParam;
  include?: _AiResponsesBasicResponseIncludable[];
  input: string | _AiResponsesMessagesResponseInput;
  instructions?: string;
  max_output_tokens?: number;
  parallel_tool_calls?: boolean;
  previous_response_id?: string;
  prompt_cache_key?: string;
  reasoning?: _AiResponsesReasoningReasoning;
  safety_identifier?: string;
  service_tier?: 'auto' | 'default' | 'flex' | 'scale' | 'priority';
  stream?: boolean;
  stream_options?: _AiResponsesBasicStreamOptions;
  temperature?: number;
  text?: _AiResponsesTextConfigResponseTextConfig;
  tool_choice?:
    | _AiResponsesToolChoiceToolChoiceOptions
    | _AiResponsesToolChoiceToolChoiceFunction;
  tools?: _AiResponsesToolDefinitionsTool[];
  top_p?: number;
  truncation?: 'auto' | 'disabled';
}

interface _AiResponsesBasicResponseConversationParam {
  id: string;
}

type _AiResponsesBasicResponseIncludable =
  | 'message.input_image.image_url'
  | 'message.output_text.logprobs';

interface _AiResponsesBasicStreamOptions {
  include_obfuscation?: boolean;
}

type _AiResponsesBasicResponseStatus =
  | 'completed'
  | 'failed'
  | 'in_progress'
  | 'cancelled'
  | 'queued'
  | 'incomplete';

interface _AiResponsesBasicResponseUsage {
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
}

interface _AiResponsesBasicResponseError {
  code:
    | 'server_error'
    | 'rate_limit_exceeded'
    | 'invalid_prompt'
    | 'vector_store_timeout'
    | 'invalid_image'
    | 'invalid_image_format'
    | 'invalid_base64_image'
    | 'invalid_image_url'
    | 'image_too_large'
    | 'image_too_small'
    | 'image_parse_error'
    | 'image_content_policy_violation'
    | 'invalid_image_mode'
    | 'image_file_too_large'
    | 'unsupported_image_media_type'
    | 'empty_image_file'
    | 'failed_to_download_image'
    | 'image_file_not_found';
  message: string;
}

interface _AiResponsesBasicResponseIncompleteDetails {
  reason?: 'max_output_tokens' | 'content_filter';
}

interface _AiResponsesBasicResponsePrompt {
  id: string;
  variables?: {
    [k: string]:
      | string
      | _AiResponsesInputContentResponseInputText
      | _AiResponsesInputContentResponseInputImage;
  };
  version?: string;
}

interface _AiResponsesTextFormatsResponseFormatText {
  type: string;
}

interface _AiResponsesTextFormatsResponseFormatTextJSONSchemaConfig {
  name: string;
  schema: {};
  type: string;
  description?: string;
  strict?: boolean;
}

interface _AiResponsesTextFormatsResponseFormatJSONObject {
  type: string;
}

interface _AiResponsesTextConfigResponseTextConfig {
  format?: _AiResponsesTextConfigResponseFormatTextConfig;
  verbosity?: 'low' | 'medium' | 'high';
}

type _AiResponsesTextConfigResponseFormatTextConfig =
  | _AiResponsesTextFormatsResponseFormatText
  | _AiResponsesTextFormatsResponseFormatTextJSONSchemaConfig
  | _AiResponsesTextFormatsResponseFormatJSONObject;

type _AiResponsesToolChoiceToolChoiceOptions = string;

interface _AiResponsesToolChoiceToolChoiceFunction {
  name: string;
  type: string;
}

type _AiResponsesToolDefinitionsTool =
  _AiResponsesToolDefinitionsResponsesFunctionTool;

interface _AiResponsesToolDefinitionsResponsesFunctionTool {
  name: string;
  parameters: {};
  strict: boolean;
  type: string;
  description?: string;
}

interface _AiResponsesToolCallsResponseFunctionToolCall {
  arguments: string;
  call_id: string;
  name: string;
  type: string;
  id?: string;
  status?: 'in_progress' | 'completed' | 'incomplete';
}

interface _AiResponsesToolCallsResponseInputItemFunctionCallOutput {
  call_id: string;
  output: string | _AiResponsesToolCallsResponseFunctionCallOutputItemList;
  type: string;
  id?: string;
  status?: 'in_progress' | 'completed' | 'incomplete';
}

type _AiResponsesToolCallsResponseFunctionCallOutputItemList =
  _AiResponsesToolCallsResponseFunctionCallOutputItem[];

type _AiResponsesToolCallsResponseFunctionCallOutputItem =
  | _AiResponsesInputContentResponseInputTextContent
  | _AiResponsesInputContentResponseInputImageContent;

interface _AiResponsesLogprobsLogprob {
  token: string;
  logprob: number;
  top_logprobs?: _AiResponsesLogprobsTopLogprob[];
}

interface _AiResponsesLogprobsTopLogprob {
  token?: string;
  logprob?: number;
}

interface _AiResponsesInputContentResponseInputText {
  text: string;
  type: string;
}

interface _AiResponsesInputContentResponseInputImage {
  detail: 'low' | 'high' | 'auto';
  type: string;
  /**
   * Base64 encoded image
   */
  image_url?: string;
}

interface _AiResponsesInputContentResponseInputTextContent {
  text: string;
  type: string;
}

interface _AiResponsesInputContentResponseInputImageContent {
  type: string;
  detail?: 'low' | 'high' | 'auto';
  /**
   * Base64 encoded image
   */
  image_url?: string;
}

type _AiResponsesInputContentResponseInputContent =
  | _AiResponsesInputContentResponseInputText
  | _AiResponsesInputContentResponseInputImage;

type _AiResponsesInputContentResponseInputMessageContentList =
  _AiResponsesInputContentResponseInputContent[];

interface _AiResponsesOutputContentResponseOutputText {
  text: string;
  type: string;
  logprobs?: _AiResponsesLogprobsLogprob[];
}

interface _AiResponsesOutputContentResponseOutputRefusal {
  refusal: string;
  type: string;
}

type _AiResponsesMessagesResponseInput =
  _AiResponsesMessagesResponseInputItem[];

type _AiResponsesMessagesResponseInputItem =
  | _AiResponsesMessagesEasyInputMessage
  | _AiResponsesMessagesResponseInputItemMessage
  | _AiResponsesMessagesResponseOutputMessage
  | _AiResponsesToolCallsResponseFunctionToolCall
  | _AiResponsesToolCallsResponseInputItemFunctionCallOutput
  | _AiResponsesReasoningResponseReasoningItem;

interface _AiResponsesMessagesEasyInputMessage {
  content: string | _AiResponsesInputContentResponseInputMessageContentList;
  role: 'user' | 'assistant' | 'system' | 'developer';
  type?: string;
}

interface _AiResponsesMessagesResponseInputItemMessage {
  content: _AiResponsesInputContentResponseInputMessageContentList;
  role: 'user' | 'system' | 'developer';
  status?: 'in_progress' | 'completed' | 'incomplete';
  type?: string;
}

interface _AiResponsesMessagesResponseOutputMessage {
  id: string;
  content: (
    | _AiResponsesOutputContentResponseOutputText
    | _AiResponsesOutputContentResponseOutputRefusal
  )[];
  role: string;
  status: 'in_progress' | 'completed' | 'incomplete';
  type: string;
}

interface _AiResponsesReasoningReasoning {
  effort?: _AiResponsesReasoningReasoningEffort;
  generate_summary?: 'auto' | 'concise' | 'detailed';
  summary?: 'auto' | 'concise' | 'detailed';
}

type _AiResponsesReasoningReasoningEffort =
  | 'minimal'
  | 'low'
  | 'medium'
  | 'high';

interface _AiResponsesReasoningResponseReasoningItem {
  id: string;
  summary: _AiResponsesReasoningResponseReasoningSummaryItem[];
  type: string;
  content?: _AiResponsesReasoningResponseReasoningContentItem[];
  encrypted_content?: string;
  status?: 'in_progress' | 'completed' | 'incomplete';
}

interface _AiResponsesReasoningResponseReasoningSummaryItem {
  text: string;
  type: string;
}

interface _AiResponsesReasoningResponseReasoningContentItem {
  text: string;
  type: string;
}

type _AiResponsesOutputResponseOutputItem =
  | _AiResponsesMessagesResponseOutputMessage
  | _AiResponsesToolCallsResponseFunctionToolCall
  | _AiResponsesReasoningResponseReasoningItem;

type _AiChatCompletionsInput =
  | ({
      /**
       * The input text prompt for the model to generate a response.
       */
      prompt: string;
    } & _AiChatCompletionsOptionsCommon)
  | ({
      /**
       * A list of messages comprising the conversation so far.
       *
       * @minItems 1
       */
      messages: [
        _AiChatCompletionsMessagesChatCompletionMessageParam,
        ..._AiChatCompletionsMessagesChatCompletionMessageParam[],
      ];
    } & _AiChatCompletionsOptionsCommon);

type _AiChatCompletionsOutput =
  | {
      /**
       * A unique identifier for the chat completion.
       */
      id: string;
      object: string;
      /**
       * Unix timestamp (seconds) of when the completion was created.
       */
      created: number;
      /**
       * The model used for the chat completion.
       */
      model: string;
      /**
       * @minItems 1
       */
      choices: [
        _AiChatCompletionsResponseChatCompletionChoice,
        ..._AiChatCompletionsResponseChatCompletionChoice[],
      ];
      usage?: _AiChatCompletionsResponseCompletionUsage;
      system_fingerprint?: string | null;
      service_tier?:
        | ('auto' | 'default' | 'flex' | 'scale' | 'priority')
        | null;
    }
  | string;

interface _AiChatCompletionsContentPartsChatCompletionContentPartText {
  type: 'text';
  text: string;
}

interface _AiChatCompletionsContentPartsChatCompletionContentPartImage {
  type: 'image_url';
  image_url: {
    url: string;
    detail?: 'auto' | 'low' | 'high';
  };
}

interface _AiChatCompletionsContentPartsChatCompletionContentPartInputAudio {
  type: 'input_audio';
  input_audio: {
    /**
     * Base64 encoded audio data.
     */
    data: string;
    format: 'wav' | 'mp3';
  };
}

interface _AiChatCompletionsContentPartsChatCompletionContentPartFile {
  type: 'file';
  file: {
    /**
     * Base64 encoded file data.
     */
    file_data?: string;
    /**
     * The ID of an uploaded file.
     */
    file_id?: string;
    filename?: string;
  };
}

interface _AiChatCompletionsContentPartsChatCompletionContentPartRefusal {
  type: 'refusal';
  refusal: string;
}

/**
 * A content part in a user message (text, image, audio, or file).
 */
type _AiChatCompletionsContentPartsChatCompletionContentPart =
  | _AiChatCompletionsContentPartsChatCompletionContentPartText
  | _AiChatCompletionsContentPartsChatCompletionContentPartImage
  | _AiChatCompletionsContentPartsChatCompletionContentPartInputAudio
  | _AiChatCompletionsContentPartsChatCompletionContentPartFile;

interface _AiChatCompletionsMessagesDeveloperMessage {
  role: 'developer';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
  name?: string;
}

interface _AiChatCompletionsMessagesSystemMessage {
  role: 'system';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
  name?: string;
}

interface _AiChatCompletionsMessagesUserMessage {
  role: 'user';
  content:
    | string
    | [
        {
          type: 'text' | 'image_url' | 'input_audio' | 'file';
          text?: string;
          image_url?: {
            url?: string;
            detail?: 'auto' | 'low' | 'high';
          };
          input_audio?: {
            data?: string;
            format?: 'wav' | 'mp3';
          };
          file?: {
            file_data?: string;
            file_id?: string;
            filename?: string;
          };
        },
        ...{
          type: 'text' | 'image_url' | 'input_audio' | 'file';
          text?: string;
          image_url?: {
            url?: string;
            detail?: 'auto' | 'low' | 'high';
          };
          input_audio?: {
            data?: string;
            format?: 'wav' | 'mp3';
          };
          file?: {
            file_data?: string;
            file_id?: string;
            filename?: string;
          };
        }[],
      ];
  name?: string;
}

interface _AiChatCompletionsMessagesAssistantMessage {
  role: 'assistant';
  content?:
    | string
    | null
    | {
        type: 'text' | 'refusal';
        text?: string;
        refusal?: string;
      }[];
  refusal?: string | null;
  name?: string;
  audio?: {
    id: string;
  };
  tool_calls?: _AiChatCompletionsToolsChatCompletionMessageToolCall[];
  function_call?: {
    name: string;
    arguments: string;
  };
}

interface _AiChatCompletionsMessagesToolMessage {
  role: 'tool';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
  tool_call_id: string;
}

interface _AiChatCompletionsMessagesFunctionMessage {
  role: 'function';
  content: string;
  name: string;
}

type _AiChatCompletionsMessagesChatCompletionMessageParam =
  | _AiChatCompletionsMessagesDeveloperMessage
  | _AiChatCompletionsMessagesSystemMessage
  | _AiChatCompletionsMessagesUserMessage
  | _AiChatCompletionsMessagesAssistantMessage
  | _AiChatCompletionsMessagesToolMessage
  | _AiChatCompletionsMessagesFunctionMessage;

interface _AiChatCompletionsToolsFunctionDefinition {
  /**
   * The name of the function to be called.
   */
  name: string;
  /**
   * A description of what the function does.
   */
  description?: string;
  /**
   * The parameters the function accepts, described as a JSON Schema object.
   */
  parameters?: {};
  /**
   * Whether to enable strict schema adherence.
   */
  strict?: boolean | null;
}

interface _AiChatCompletionsToolsChatCompletionFunctionTool {
  type: 'function';
  function: _AiChatCompletionsToolsFunctionDefinition;
}

interface _AiChatCompletionsToolsChatCompletionCustomTool {
  type: 'custom';
  custom: {
    name: string;
    description?: string;
    format?:
      | {
          type: 'text';
        }
      | {
          type: 'grammar';
          grammar: {
            definition: string;
            syntax: 'lark' | 'regex';
          };
        };
  };
}

type _AiChatCompletionsToolsChatCompletionTool =
  | _AiChatCompletionsToolsChatCompletionFunctionTool
  | _AiChatCompletionsToolsChatCompletionCustomTool;

interface _AiChatCompletionsToolsChatCompletionMessageFunctionToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    /**
     * JSON-encoded arguments string.
     */
    arguments: string;
  };
}

interface _AiChatCompletionsToolsChatCompletionMessageCustomToolCall {
  id: string;
  type: 'custom';
  custom: {
    name: string;
    input: string;
  };
}

type _AiChatCompletionsToolsChatCompletionMessageToolCall =
  | _AiChatCompletionsToolsChatCompletionMessageFunctionToolCall
  | _AiChatCompletionsToolsChatCompletionMessageCustomToolCall;

/**
 * Controls which (if any) tool is called by the model. 'none' = no tools, 'auto' = model decides, 'required' = must call a tool.
 */
type _AiChatCompletionsToolsChatCompletionToolChoiceOption =
  | ('none' | 'auto' | 'required')
  | {
      type: 'function';
      function: {
        name: string;
      };
    }
  | {
      type: 'custom';
      custom: {
        name: string;
      };
    }
  | {
      type: 'allowed_tools';
      allowed_tools: {
        mode: 'auto' | 'required';
        tools: {}[];
      };
    };

/**
 * Specifies the format the model must output.
 */
type _AiChatCompletionsOptionsResponseFormat =
  | {
      type: 'text';
    }
  | {
      type: 'json_object';
    }
  | {
      type: 'json_schema';
      json_schema: {
        name: string;
        description?: string;
        schema?: {};
        strict?: boolean | null;
      };
    };

interface _AiChatCompletionsOptionsStreamOptions {
  include_usage?: boolean;
  include_obfuscation?: boolean;
}

interface _AiChatCompletionsOptionsPredictionContent {
  type: 'content';
  content:
    | string
    | {
        type: 'text';
        text: string;
      }[];
}

/**
 * Parameters for audio output. Required when modalities includes 'audio'.
 */
interface _AiChatCompletionsOptionsAudioParams {
  voice:
    | string
    | {
        id: string;
      };
  format: 'wav' | 'aac' | 'mp3' | 'flac' | 'opus' | 'pcm16';
}

/**
 * Options for the web search tool (when using built-in web search).
 */
interface _AiChatCompletionsOptionsWebSearchOptions {
  search_context_size?: 'low' | 'medium' | 'high';
  user_location?: {
    type: 'approximate';
    approximate: {
      city?: string;
      country?: string;
      region?: string;
      timezone?: string;
    };
  };
}

interface _AiChatCompletionsOptionsCommon {
  /**
   * ID of the model to use (e.g. '@cf/zai-org/glm-4.7-flash, etc').
   */
  model?: string;
  audio?: _AiChatCompletionsOptionsAudioParams;
  /**
   * Penalizes new tokens based on their existing frequency in the text so far.
   */
  frequency_penalty?: number | null;
  /**
   * Modify the likelihood of specified tokens appearing in the completion. Maps token IDs to bias values from -100 to 100.
   */
  logit_bias?: {} | null;
  /**
   * Whether to return log probabilities of the output tokens.
   */
  logprobs?: boolean | null;
  /**
   * How many top log probabilities to return at each token position (0-20). Requires logprobs=true.
   */
  top_logprobs?: number | null;
  /**
   * Deprecated in favor of max_completion_tokens. The maximum number of tokens to generate.
   */
  max_tokens?: number | null;
  /**
   * An upper bound for the number of tokens that can be generated for a completion.
   */
  max_completion_tokens?: number | null;
  /**
   * Set of 16 key-value pairs that can be attached to the object.
   */
  metadata?: {} | null;
  /**
   * Output types requested from the model (e.g. ['text'] or ['text', 'audio']).
   */
  modalities?: ('text' | 'audio')[] | null;
  /**
   * How many chat completion choices to generate for each input message.
   */
  n?: number | null;
  /**
   * Whether to enable parallel function calling during tool use.
   */
  parallel_tool_calls?: boolean;
  prediction?: _AiChatCompletionsOptionsPredictionContent;
  /**
   * Penalizes new tokens based on whether they appear in the text so far.
   */
  presence_penalty?: number | null;
  /**
   * Constrains effort on reasoning for reasoning models (o1, o3-mini, etc.).
   */
  reasoning_effort?: ('low' | 'medium' | 'high') | null;
  chat_template_kwargs?: {
    /**
     * Whether to enable reasoning, enabled by default.
     */
    enable_thinking?: boolean;
    /**
     * If false, preserves reasoning context between turns.
     */
    clear_thinking?: boolean;
  };
  response_format?: _AiChatCompletionsOptionsResponseFormat;
  /**
   * If specified, the system will make a best effort to sample deterministically.
   */
  seed?: number | null;
  /**
   * Specifies the processing type used for serving the request.
   */
  service_tier?: ('auto' | 'default' | 'flex' | 'scale' | 'priority') | null;
  /**
   * Up to 4 sequences where the API will stop generating further tokens.
   */
  stop?:
    | null
    | string
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string];
  /**
   * Whether to store the output for model distillation / evals.
   */
  store?: boolean | null;
  /**
   * If true, partial message deltas will be sent as server-sent events.
   */
  stream?: boolean | null;
  stream_options?: _AiChatCompletionsOptionsStreamOptions;
  /**
   * Sampling temperature between 0 and 2.
   */
  temperature?: number | null;
  tool_choice?: _AiChatCompletionsToolsChatCompletionToolChoiceOption;
  /**
   * A list of tools the model may call.
   */
  tools?: _AiChatCompletionsToolsChatCompletionTool[];
  /**
   * Nucleus sampling: considers the results of the tokens with top_p probability mass.
   */
  top_p?: number | null;
  /**
   * A unique identifier representing your end-user, for abuse monitoring.
   */
  user?: string;
  web_search_options?: _AiChatCompletionsOptionsWebSearchOptions;
  function_call?:
    | ('none' | 'auto')
    | {
        name: string;
      };
  /**
   * @minItems 1
   * @maxItems 128
   */
  functions?: [
    _AiChatCompletionsToolsFunctionDefinition,
    ..._AiChatCompletionsToolsFunctionDefinition[],
  ];
}

interface _AiChatCompletionsResponseCompletionUsage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  prompt_tokens_details?: {
    cached_tokens?: number;
    audio_tokens?: number;
  };
  completion_tokens_details?: {
    reasoning_tokens?: number;
    audio_tokens?: number;
    accepted_prediction_tokens?: number;
    rejected_prediction_tokens?: number;
  };
}

interface _AiChatCompletionsResponseChatCompletionTokenLogprob {
  token: string;
  logprob: number;
  bytes: number[] | null;
  top_logprobs: {
    token: string;
    logprob: number;
    bytes: number[] | null;
  }[];
}

interface _AiChatCompletionsResponseChatCompletionAudio {
  id: string;
  /**
   * Base64 encoded audio bytes.
   */
  data: string;
  expires_at: number;
  transcript: string;
}

interface _AiChatCompletionsResponseChatCompletionResponseMessage {
  role: 'assistant';
  content: string | null;
  refusal: string | null;
  annotations?: {
    type: 'url_citation';
    url_citation: {
      url: string;
      title: string;
      start_index: number;
      end_index: number;
    };
  }[];
  audio?: _AiChatCompletionsResponseChatCompletionAudio;
  tool_calls?: _AiChatCompletionsToolsChatCompletionMessageToolCall[];
  function_call?: {
    name: string;
    arguments: string;
  } | null;
}

interface _AiChatCompletionsResponseChatCompletionChoice {
  index: number;
  message: _AiChatCompletionsResponseChatCompletionResponseMessage;
  finish_reason:
    | 'stop'
    | 'length'
    | 'tool_calls'
    | 'content_filter'
    | 'function_call';
  logprobs: {
    content?: _AiChatCompletionsResponseChatCompletionTokenLogprob[] | null;
    refusal?: _AiChatCompletionsResponseChatCompletionTokenLogprob[] | null;
  } | null;
}
