// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

// Generates `types/defines/ai-models.d.ts` from the staging catalog dump.
//
// Each public, non-hidden catalog entry with a custom JSON-schema produces
// three top-level declarations:
//
//   export type Ai_Cf_Foo_Bar_Input  = ...;
//   export type Ai_Cf_Foo_Bar_Output = ...;
//   export interface Base_Ai_Cf_Foo_Bar {
//     inputs: Ai_Cf_Foo_Bar_Input;
//     postProcessedOutputs: Ai_Cf_Foo_Bar_Output;
//   }
//
// Cross-block `$ref`s into the shared schemas (e.g.
// `textGenerationOptions#/common`) are intercepted by the same custom resolver
// used by `generateSharedSchemas`, so the generated per-model types reference
// the shared type aliases instead of re-inlining them.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { schemaBlocks } from './input/schemas/index.ts';
import {
  buildTypeNameMap,
  expandMerge,
  modelToClass,
  unwrapPropertyBag,
} from './helpers.ts';
import { makeRefResolver } from './generate-shared.ts';

interface CatalogEntry {
  model_name: string;
  task_name: string;
  schema: string;
  is_private: number;
  hide_from_catalog: number;
  stop_serving_after_deprecation?: number;
}

/**
 * Map a catalog `task_name` to the generic `BaseAi*` interface declared in
 * `types/defines/ai.d.ts`. Models that have no custom JSON-schema fall back to
 * one of these task-default types in the generated `AiModels` interface.
 *
 * The mapping is the source of truth in the existing hand-rolled `AiModels`
 * interface (see `types/defines/ai.d.ts`). `Dumb Pipe` is intentionally
 * absent: it has no public TypeScript binding. The only catalog entry with
 * task `Dumb Pipe` (`@cf/pipecat-ai/smart-turn-v2`) carries a custom schema
 * and therefore uses its `Base_Ai_Cf_*` interface; if a future Dumb Pipe
 * model lacks a custom schema we drop it from `AiModels` and record a skip.
 */
const TASK_TO_BASE_AI: Record<string, string> = {
  'Text Generation': 'BaseAiTextGeneration',
  'Text-to-Image': 'BaseAiTextToImage',
  'Text Embeddings': 'BaseAiTextEmbeddings',
  'Text Classification': 'BaseAiTextClassification',
  'Image Classification': 'BaseAiImageClassification',
  'Image-to-Text': 'BaseAiImageToText',
  Summarization: 'BaseAiSummarization',
  Translation: 'BaseAiTranslation',
  'Automatic Speech Recognition': 'BaseAiAutomaticSpeechRecognition',
  'Text-to-Speech': 'BaseAiTextToSpeech',
  'Object Detection': 'BaseAiObjectDetection',
  'Image-Text-to-Text': 'BaseAiImageTextToText',
  'Multimodal Embeddings': 'BaseAiMultimodalEmbeddings',
};

const HEADER = `// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0
//
// AUTO-GENERATED by types/scripts/ai-types/generate.ts
// DO NOT EDIT MANUALLY. Run \`pnpm generate\` to regenerate.

`;

export interface GenerateModelsResult {
  /** The generated TypeScript source. */
  content: string;
  /** Names of models that successfully generated. */
  generated: string[];
  /** Names of models that were skipped, with the reason. */
  skipped: Array<{ model: string; reason: string }>;
}

export async function generateModels(): Promise<GenerateModelsResult> {
  const dumpPath = path.resolve(
    import.meta.dirname,
    './input/staging_config_dump.json'
  );
  const dump = JSON.parse(readFileSync(dumpPath, 'utf8')) as {
    result: { catalog: CatalogEntry[] };
  };
  const catalog = dump.result.catalog;

  // Models eligible for the `AiModels` interface: public, not hidden, and
  // not deprecated past the point of being served. The `AiModels` mapping
  // covers both models with custom schemas (which get `Base_Ai_Cf_*`) and
  // those without (which fall back to a generic `BaseAi*` for their task).
  const eligibleModels = catalog.filter(
    (m) =>
      m.is_private === 0 &&
      m.hide_from_catalog === 0 &&
      m.stop_serving_after_deprecation !== 1
  );

  // Narrower set: only models with a custom JSON-schema get per-model
  // Input/Output/Base type declarations. The rest are pure mapping entries.
  const modelsWithSchema = eligibleModels.filter((m) => Boolean(m.schema));

  const typeNames = buildTypeNameMap(schemaBlocks);
  const $refOptions = makeRefResolver(typeNames);

  const generated: string[] = [];
  const skipped: Array<{ model: string; reason: string }> = [];
  let content = HEADER;

  for (const model of modelsWithSchema) {
    const { baseClass, inputClass, outputClass } = modelToClass(
      model.model_name
    );

    let schema: { input?: unknown; output?: unknown };
    try {
      schema = JSON.parse(model.schema);
    } catch (e) {
      skipped.push({
        model: model.model_name,
        reason: `failed to parse schema JSON: ${e}`,
      });
      continue;
    }

    // Fast-path: models whose entire input/output is `$ref:
    // "chatCompletions#/input"` / `chatCompletions#/output` (e.g. zai/glm,
    // moonshotai/kimi, etc.) are aliased directly to the shared chat
    // completions types. This matches the convention in the existing
    // hand-rolled `types/defines/ai.d.ts`.
    //
    // The shared types are non-exported (internal) -- they live in
    // `ai-shared-schemas.d.ts` as `interface _AiChatCompletionsInput`
    // declarations. We reference them by their underscored names; the
    // per-model alias remains exported so users can name it directly.
    if (isChatCompletionsSchema(schema)) {
      content += `export type ${inputClass} = _AiChatCompletionsInput;\n`;
      content += `export type ${outputClass} = _AiChatCompletionsOutput;\n`;
      content += `export interface ${baseClass} {\n`;
      content += `  inputs: ${inputClass};\n`;
      content += `  postProcessedOutputs: ${outputClass};\n`;
      content += `}\n\n`;
      generated.push(model.model_name);
      continue;
    }

    // Generic case: compile the input and output schemas. The batch wrapper
    // (the oneOf branch with a `requests` array) is stripped: batch handling
    // is now done by the `run()` overload, not per-model types.
    //
    // We also recursively strip every `title` from the schema before
    // compiling. `json-schema-to-typescript` hoists any titled sub-schema
    // into its own top-level declaration; without stripping, models that
    // happen to share branch titles (e.g. "Prompt", "Messages", "Async
    // response") emit duplicate top-level identifiers that TypeScript
    // rejects. Per-model schemas are compiled in isolation, so inlining the
    // anonymous branch types is the right tradeoff.
    const inputForGen = stripTitles(stripBatchWrapper(schema.input));
    const outputForGen = stripTitles(schema.output);

    try {
      const inputTs = await compile(
        expandMerge(unwrapPropertyBag(inputForGen)) as Parameters<
          typeof compile
        >[0],
        inputClass,
        {
          bannerComment: '',
          additionalProperties: false,
          $refOptions,
          style: {
            printWidth: 80,
            tabWidth: 2,
            singleQuote: true,
            trailingComma: 'es5',
          },
        }
      );
      const outputTs = await compile(
        expandMerge(unwrapPropertyBag(outputForGen)) as Parameters<
          typeof compile
        >[0],
        outputClass,
        {
          bannerComment: '',
          additionalProperties: false,
          $refOptions,
          style: {
            printWidth: 80,
            tabWidth: 2,
            singleQuote: true,
            trailingComma: 'es5',
          },
        }
      );

      // Strip `export` from every hoisted helper type produced by
      // `json-schema-to-typescript`. Only the three top-level names we
      // declare ourselves (`inputClass`, `outputClass`, `baseClass`) are
      // part of the public API. Any other hoisted interface/type alias is
      // an internal helper and must not be importable.
      const topLevelExported = new Set([inputClass, outputClass, baseClass]);
      const stripNonTopLevelExports = (src: string): string =>
        src
          .split('\n')
          .map((line) => {
            const m = line.match(/^export (interface|type) (\w+)/);
            if (m && !topLevelExported.has(m[2]!)) {
              return line.replace(/^export /, '');
            }
            return line;
          })
          .join('\n');

      content += stripNonTopLevelExports(inputTs);
      content += stripNonTopLevelExports(outputTs);
      content += `export interface ${baseClass} {\n`;
      content += `  inputs: ${inputClass};\n`;
      content += `  postProcessedOutputs: ${outputClass};\n`;
      content += `}\n\n`;
      generated.push(model.model_name);
    } catch (e) {
      skipped.push({
        model: model.model_name,
        reason: `compile failed: ${e instanceof Error ? e.message : e}`,
      });
      continue;
    }
  }

  // Build the `AiModels` interface that maps model name -> Base type. Models
  // with custom schemas reference the generated `Base_Ai_Cf_*` interfaces;
  // models without a schema fall back to a generic `BaseAi*` selected by
  // task name (declared in the hand-rolled `ai.d.ts`).
  const generatedSet = new Set(generated);
  const previousModels = extractExistingModels();
  const newModels: string[] = [];
  const aiModelsEntries: Array<{ name: string; type: string }> = [];

  for (const model of eligibleModels) {
    if (generatedSet.has(model.model_name)) {
      const { baseClass } = modelToClass(model.model_name);
      aiModelsEntries.push({ name: model.model_name, type: baseClass });
    } else {
      const baseAi = TASK_TO_BASE_AI[model.task_name];
      if (baseAi === undefined) {
        // No public TypeScript binding for this task (e.g. `Dumb Pipe`).
        // Record the skip and drop the model from `AiModels`; existing
        // hand-rolled types don't expose it either.
        skipped.push({
          model: model.model_name,
          reason: `no BaseAi mapping for task "${model.task_name}" and no custom schema`,
        });
        continue;
      }
      aiModelsEntries.push({ name: model.model_name, type: baseAi });
    }
    if (!previousModels.has(model.model_name)) {
      newModels.push(model.model_name);
    }
  }

  if (newModels.length > 0) {
    console.log(`\nNEW MODELS (not in previous ai.d.ts):`);
    for (const m of newModels) console.log(`  - ${m}`);
    content += `// New since previous generation:\n`;
    for (const m of newModels) content += `//   - ${m}\n`;
  }

  content += `export interface AiModels {\n`;
  for (const { name, type } of aiModelsEntries) {
    content += `  '${name}': ${type};\n`;
  }
  content += `}\n`;

  // Trim trailing whitespace so the file matches prettier's formatting (a
  // single trailing newline, no blank line before EOF).
  return {
    content: content.replace(/\s+$/, '\n'),
    generated,
    skipped,
  };
}

/**
 * Read the existing hand-rolled `types/defines/ai.d.ts` and extract the set
 * of model names that appear in its `AiModels` interface. Used purely to
 * highlight which models in the new generated output are new since the last
 * hand-rolled version.
 *
 * Returns an empty set if the file is missing or the interface can't be
 * located -- this is a diagnostic-only signal, never load-bearing.
 */
function extractExistingModels(): Set<string> {
  const aiDtsPath = path.resolve(
    import.meta.dirname,
    '../../defines/ai.d.ts'
  );
  let src: string;
  try {
    src = readFileSync(aiDtsPath, 'utf8');
  } catch {
    return new Set();
  }
  const start = src.indexOf('export interface AiModels');
  if (start === -1) return new Set();
  const end = src.indexOf('}', start);
  if (end === -1) return new Set();
  const body = src.slice(start, end);
  const names = new Set<string>();
  const re = /'(@[^']+)':/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(body)) !== null) {
    if (m[1] !== undefined) names.add(m[1]);
  }
  return names;
}

/**
 * Detect schemas of the form `{ input: { $ref: "chatCompletions#/input" },
 * output: { $ref: "chatCompletions#/output" } }`. These models delegate their
 * entire input/output shape to the shared `chatCompletions` block, so we just
 * alias their per-model types to the shared `AiChatCompletionsInput` /
 * `AiChatCompletionsOutput` instead of recompiling.
 *
 * We intentionally only recognize the exact `chatCompletions` block here --
 * other schemas that happen to contain "chatCompletions" elsewhere (e.g. a
 * partial `$ref` into a different block, or a string literal in a description)
 * go through the generic compile path.
 */
function isChatCompletionsSchema(schema: {
  input?: unknown;
  output?: unknown;
}): boolean {
  function isCcRef(v: unknown, hash: string): boolean {
    if (v === null || typeof v !== 'object') return false;
    const ref = (v as Record<string, unknown>).$ref;
    return (
      typeof ref === 'string' &&
      ref.replace(/^.*\/schemas\//, '') === `chatCompletions${hash}`
    );
  }
  return isCcRef(schema.input, '#/input') && isCcRef(schema.output, '#/output');
}

/**
 * Recursively remove every `title` and `$id` field from a JSON-schema-shaped
 * value.
 *
 * `json-schema-to-typescript` treats both a `title` and a `$id` as a request
 * to hoist the sub-schema into its own top-level declaration. Many per-model
 * schemas reuse generic branch titles like "Prompt", "Messages", or "Async
 * response", and several text-generation schemas carry a `$id` of
 * `http://ai.cloudflare.com/schemas/textGenerationInput` on the root input
 * object. Both would otherwise produce duplicate `export` identifiers across
 * models. Inlining is safe here because each per-model file emits three
 * named declarations anyway (Input / Output / Base).
 */
function stripTitles(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripTitles);
  if (value === null || typeof value !== 'object') return value;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    if (k === 'title' || k === '$id') continue;
    out[k] = stripTitles(v);
  }
  return out;
}

/**
 * Strip the batch-wrapper variant from a model's input schema.
 *
 * Several text-generation models expose a `oneOf` whose second branch is a
 * batch wrapper -- an object with a `requests` array carrying the per-item
 * payloads. Batch handling is now done by the `run()` method overload (one of
 * the hand-rolled overloads in `types/defines/ai.d.ts`), so we drop the
 * wrapper branch from the per-model type. If only one branch remains we
 * unwrap the `oneOf` entirely.
 */
function stripBatchWrapper(input: unknown): unknown {
  if (input === null || typeof input !== 'object') return input;
  const obj = input as Record<string, unknown>;
  // Models use either `oneOf` (text-generation) or `anyOf` (chat-completions)
  // to represent the single-request / batch-of-requests split.
  const variantKey = Array.isArray(obj.oneOf)
    ? 'oneOf'
    : Array.isArray(obj.anyOf)
      ? 'anyOf'
      : null;
  if (variantKey === null) return input;
  const branches = obj[variantKey] as unknown[];

  const filtered = branches.filter((branch) => {
    if (branch === null || typeof branch !== 'object') return true;
    const b = branch as Record<string, unknown>;
    // Detect batch wrapper: has `requests` in properties.
    const props = b.properties as Record<string, unknown> | undefined;
    if (props && 'requests' in props) return false;
    // Detect explicit "Async Batch" title.
    if (b.title === 'Async Batch') return false;
    return true;
  });

  if (filtered.length === branches.length) {
    // Nothing was a batch wrapper; leave the schema alone.
    return input;
  }
  if (filtered.length === 1) {
    // Only one branch left -- merge it into the parent so we don't emit a
    // single-element union. We preserve sibling keys (e.g. the parent `type`
    // and `description`) so the resulting schema is still well-formed.
    const branch = filtered[0] as Record<string, unknown>;
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj)) {
      if (k === variantKey) continue;
      result[k] = v;
    }
    for (const [k, v] of Object.entries(branch)) {
      result[k] = v;
    }
    return result;
  }
  return { ...obj, [variantKey]: filtered };
}
