// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

// Generates `types/defines/ai-shared-schemas.d.ts` from the vendored
// `schemaBlocks` (see ./input/schemas/index.ts).
//
// Each block is a plain object keyed by `$id` plus one or more sub-schema
// names. We compile each named sub-schema as its own top-level TypeScript
// type. Cross-block `$ref`s (e.g. "chatCompletionsTools#/FunctionDefinition")
// are intercepted by a custom `$RefParser` resolver and replaced with a stub
// schema that uses the `tsType` escape hatch supported by
// `json-schema-to-typescript` -- this causes the generator to emit a literal
// type alias reference instead of inlining the full referenced schema.

import { compile, type Options } from 'json-schema-to-typescript';
import { schemaBlocks } from './input/schemas/index.ts';
import {
  buildTypeNameMap,
  expandMerge,
  schemaIdToTypeName,
  unwrapPropertyBag,
} from './helpers.ts';

const HEADER = `// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0
//
// AUTO-GENERATED by types/scripts/ai-types/generate.ts
// DO NOT EDIT MANUALLY. Run \`pnpm generate\` to regenerate.

`;

/**
 * Build a `$RefParser` resolver that rewrites cross-block `$ref`s of the form
 * `blockName#/Key` (or the equivalent `http://ai.cloudflare.com/schemas/...`
 * URL form) into `tsType` stubs that
 * [`json-schema-to-typescript`](https://github.com/bcherny/json-schema-to-typescript)
 * emits as bare type-alias references instead of inlining the full schema.
 *
 * Shared between `generateSharedSchemas` (which compiles the blocks themselves)
 * and `generateModels` (which compiles per-model schemas that may $ref into
 * the shared blocks). The behaviour is identical in both contexts.
 */
export function makeRefResolver(
  typeNames: Map<string, string>
): Options['$refOptions'] {
  // Build a set of known short block ids (e.g. "textGenerationPrompts").
  // The vendored schemas use bare refs like `textGenerationPrompts#/Key` that
  // have no URL scheme. By the time our resolver runs, ref-parser has
  // resolved them against the cwd, producing a path like
  // `/abs/path/textGenerationPrompts`. We recognize them by the basename of
  // the resolved URL combined with the hash fragment.
  const shortIds = new Set<string>();
  for (const block of schemaBlocks) {
    const blockId = block.$id;
    if (typeof blockId === 'string' && blockId.length > 0) {
      shortIds.add(blockId.replace(/^.*\/schemas\//, ''));
    }
  }

  /**
   * Recover the canonical short form of a $ref ("blockName#/Key") from a
   * (file.url, file.hash) pair, regardless of whether ref-parser preserved
   * the original short ref or resolved it against the cwd.
   */
  function shortFormFromFile(file: {
    url: string;
    hash: string;
  }): string | undefined {
    const hash = file.hash || '';
    if (!hash.startsWith('#/')) return undefined;
    const url = file.url || '';
    // Cloudflare-namespaced URL form
    const schemasMatch = url.match(/\/schemas\/([^/?#]+)$/);
    if (schemasMatch) return schemasMatch[1] + hash;
    // Bare short form that ref-parser resolved against cwd; the basename is
    // the block name. Check it's actually one of ours.
    const basenameMatch = url.match(/([^/\\]+)$/);
    if (basenameMatch && shortIds.has(basenameMatch[1]!)) {
      return basenameMatch[1]! + hash;
    }
    return undefined;
  }

  return {
    resolve: {
      // Disable the http resolver -- our $refs that look like
      // "http://ai.cloudflare.com/..." aren't real URLs we want to fetch.
      http: false,
      aiSharedSchemas: {
        order: 1,
        canRead: (file: { url: string; hash: string }): boolean => {
          return shortFormFromFile(file) !== undefined;
        },
        read(file: { url: string; hash: string }): string {
          // Resolvers operate on the (file-level) URL only -- the hash
          // fragment is applied by the parser afterwards to pick a
          // sub-schema out of whatever we return. So we need to return a
          // top-level schema whose JSON pointer at `hash` resolves to the
          // tsType stub.
          //
          // We don't actually know which sub-schema the consumer is going
          // to dereference (canRead is called per-file, not per-ref), so
          // we synthesize a schema where every key maps to the right
          // stub. Easier: return a single object that pre-bakes all
          // sub-schemas of this block as tsType stubs.
          const url = file.url || '';
          const schemasMatch = url.match(/\/schemas\/([^/?#]+)$/);
          const basenameMatch = url.match(/([^/\\]+)$/);
          const blockShort =
            schemasMatch?.[1] ??
            (basenameMatch && shortIds.has(basenameMatch[1]!)
              ? basenameMatch[1]!
              : undefined);
          if (!blockShort) {
            throw new Error(`Unrecognized shared schema $ref source: ${url}`);
          }
          const stub: Record<string, unknown> = {};
          for (const block of schemaBlocks) {
            const blockId = block.$id;
            if (typeof blockId !== 'string') continue;
            if (blockId.replace(/^.*\/schemas\//, '') !== blockShort) continue;
            for (const key of Object.keys(block)) {
              if (key === '$id') continue;
              const lookup = typeNames.get(`${blockShort}#/${key}`);
              if (!lookup) {
                throw new Error(
                  `No type name registered for ${blockShort}#/${key}`
                );
              }
              stub[key] = { tsType: lookup };
            }
          }
          return JSON.stringify(stub);
        },
      },
    },
  };
}

export async function generateSharedSchemas(): Promise<string> {
  const typeNames = buildTypeNameMap(schemaBlocks);
  let content = HEADER;

  // Build the custom $ref resolver once and reuse it across all compile()
  // calls.
  const $refOptions = makeRefResolver(typeNames);

  for (const block of schemaBlocks) {
    const blockId = block.$id;
    if (typeof blockId !== 'string' || blockId.length === 0) continue;

    for (const [key, value] of Object.entries(block)) {
      if (key === '$id') continue;

      const typeName = schemaIdToTypeName(blockId, key);
      // json-schema-to-typescript prefers `schema.title` over the `name`
      // argument when picking the top-level type's name. We want our derived
      // typeName to win, so strip the top-level `title` from a shallow clone
      // before compiling. Nested titles are left intact -- they help generate
      // sensible names for hoisted anonymous sub-types.
      //
      // Pre-process the schema to expand any Cabidela `$merge` constructs
      // into standard JSON Schema `allOf` so json-schema-to-typescript can
      // produce proper intersection types. Also unwrap property-bag shaped
      // sub-schemas (Cabidela's convention of storing a flat field map
      // instead of a full `{type:"object", properties:{...}}` schema).
      const unwrapped = unwrapPropertyBag(value);
      const expanded = expandMerge(unwrapped) as Record<string, unknown>;
      const rootSchema = { ...expanded };
      delete rootSchema.title;
      const ts = await compile(
        rootSchema as Parameters<typeof compile>[0],
        typeName,
        {
          bannerComment: '',
          additionalProperties: false,
          $refOptions,
          // Match the workerd repo's .prettierrc.json so the generated
          // file is prettier-clean out of the box.
          style: {
            printWidth: 80,
            tabWidth: 2,
            singleQuote: true,
            trailingComma: 'es5',
          },
        }
      );
      // Strip `export` from every top-level declaration in this block. Shared
      // schema types are internal: they remain referenced structurally by the
      // per-model top-level types in `ai-models.d.ts`, but are not part of
      // the public API and cannot be imported by name.
      const stripped = ts
        .replace(/^export interface /gm, 'interface ')
        .replace(/^export type /gm, 'type ');
      content += stripped + '\n';
    }
  }

  // Trim trailing whitespace so the file matches prettier's formatting (a
  // single trailing newline, no blank line before EOF).
  return content.replace(/\s+$/, '\n');
}
